name: wtracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_native_splash: ^2.2.16
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.1
  line_awesome_flutter: ^2.0.0
  table_calendar: ^3.0.0
  duration_picker: "^1.0.0"
  flutter_cupertino_date_picker_fork: ^1.0.7
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  size: 300
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/splash_logos/splash-icon-dark.png
  image_dark: assets/images/splash_logos/splash-icon-light.png

  android_12:
    icon_background_color: "#f7f6f1"
    icon_background_color_dark: "#272727"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/onboarding_images/
    - assets/images/profile/
