const List<String> exerciseList = [
  "Fekvenyomás rúddal",
  "Fekvenyomás kézi súlyzókkal",
  "Guggolás",
  "Felhúzás",
  "Kitörés kézi súlyzókkal",
  "Kitörés rúddal",
  "Vállnyomás rúddal",
  "Vállnyomás kézi súlyzókkal",
  "Húzódzkodás",
  "Fekvőtámasz",
  "Tolódzkodás",
  "Evezés rúddal",
  "Evezés rúddal kézi súlyzóval",
  "Karhajlítás rúddal",
  "Karhajlítás kézi súlyzóval",
  "Lehúzás csigás gépen rúddal",
  "Lábtoló gépen",
  "Comb hajlítás gépen",
  "Térdhajlítás gépen",
  "Kézi súlyzóval végzett vádliemelés",
  "Gépen végzett vádliemelés",
  "Vállnyomás rúddal",
  "Vállnyomás kézi súlyzókkal",
  "Oldalemelés",
  "Előreemelés",
  "Ferde padon fekvenyomás",
  "Mellnyomás gépen",
  "Kábelgépen végzett keresztezés",
  "Felülések",
  "Hasprések",
  "Plank",
  "Hegymászó",
  "Burpee",
  "Kettlebell lendítés",
  "Dobozugrás",
  "Lépcsőzés",
  "Csípőemelés",
  "Koponyatörő rúddal",
  "Koponyatörő kézi súlyzókkal",
  "Kalapácsfogású bicepsz gyakorlat",
  "Függő lábemelés",
  "Pec-deck gép",
  "Szumó guggolás rúddal",
  "Szumó guggolás kézi súlyzókkal",
  "Rickshaw Carry",
  "Egy lábon végzett lábnyomás gépen",
  "Landmine twist",
  "Súlyozott húzódzkodás",
  "T-rúd evezés fogantyúval",
  "Csuklófordítás kézi súlyzóval",
  "Oldalemelés Kézi súlyzóval",
  "Tricepsz merülés",
  "Tapsolós fekvőtámasz",
  "Fordított sor hevederrel",
  "Guggolás forgatással",
  "Fejállás nyomás",
  "Egy lábon végzett burpee",
  "Hegymászó",
  "Pókember fekvőtámasz",
  "Pisztoly guggolás",
  "Gyémánt fekvőtámasz"
];
